### ISSUE TITLE
[front] TODO

### ISSUE THREAD

**Issue by reyeon1209** [reyeon1209/PressCheck#6]
**Home 화면**

- [x] 더보기

- [x] 조선일보 -> 한겨레 수정

- [x] tag 자체 CSS 수정

- [x] aggregate color 수정

- [x] 전체 Frame을 react-split 사용해서 수정

- [x] 가장 많이 본 뉴스 TOP 5 정렬 수정 (한 줄, 두 줄인 경우 정렬 다름)

- [x] ?시 ~ ?시까지 집계한 뉴스리스트인지 시간 수정

- [x] 카테고리/언론사 삭제

- [x] 뉴스 클릭 시, 해당 뉴스의 분석 화면으로 link

**News > NewsList 화면**

- [x] 조선일보 -> 한겨레 수정

- [x] tag 자체 CSS 수정

- [x] Table CSS 수정

- [x] aggregate color 수정

- [x] Test Data 수정

- [x] 기자 부분 수정

- [x] ?시 ~ ?시까지 집계한 뉴스리스트인지 시간 수정

- [x] 카테고리 처리

- [x] 언론사 처리

- [x] 뉴스 클릭 시, 해당 뉴스의 분석 화면으로 link

**News > Analyze 화면**

- [x] 차이점 키워드 유사한 뉴스 Table에 추가

- [x] 유사한 뉴스 Table 역순으로 수정

- [x] 전체 CSS

- [x] Email 전송 화면 깨짐 수정

- [x] 선택된 요약 버튼 색깔 바뀌게

- [x] ?시 ~ ?시까지 집계한 뉴스리스트인지 시간 수정

- [x] 유사한 뉴스 클릭 시, 해당 뉴스의 분석 화면으로 link

- [x] img_src 없을 때 처리

**Today's 화면**

- [x] 전체 CSS 수정

- [x] 선택된 탭 색깔 바뀌게

- [x] DB 연결

- [x] 오늘의 주요 기사 요약의 뉴스 제목 클릭 시, 해당 뉴스의 분석 화면으로 link

- [x] 키워드 추이 (시간 클릭 시, 해당 시간의 키워드 추이 보여주게)
