### ISSUE TITLE
[bakend] TODO

### ISSUE THREAD

**Issue by PapyrusNotes** [reyeon1209/PressCheck#7]
- [x] collect.py-article-'uploaded'크롤링

- [x] collect.py-article-'updated'크롤링

- [x] collect.py-article-'editor'크롤링

- [x] collect.py-article-'img_src'크롤링

- [x] 예외처리,에러처리 함수 만들기

- [x] mostRead

- [x] updateSimilarity 

- [ ] DeleteAll (수정 예정)

- [ ] Todays.py 10%

- [ ] 코드 batch.py로 통합, 테스트

@choi95
